### ISSUE TITLE
Admirer 

### ISSUE THREAD

**Issue by solomonchidera** [aallali/aallali#1]
hey man, solomon here opening this issue to say i admier your work bro, cool projects

would love to connect with you maybe on discord if that's okay /hats off/

**Comment by aallali** [comment]
Hi @solomonchidera, happy to hear that, that doesn't happened very often, glad you enjoyed the repos, 
Here is my discord id: `is_golden`, will be happy to add you there

**Comment by solomonchidera** [comment]
alright bro, will send you a friend request now

**Comment by solomonchidera** [comment]
alright bro, I just sent you a friend request now
name is `solochidera`
